require_relative '../config/environment'

def setup_seed_data
wines =   [{"wine"=>"Rivers-Marie, Lore Vineyard Cabernet Sauvignon, Oakville",
 "wine_id"=>121092,
 "wine_slug"=>"rivers-marie-lore-vineyard-cabernet-sauvignon-oakville",
 "appellation"=>"Oakville",
 "appellation_slug"=>"oakville",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["California"],
 "country"=>"Usa",
 "classification"=>nil,
 "vintage"=>"2015",
 "date"=>"2018-10-31",
 "is_primeurs"=>false,
 "score"=>96.17,
 "confidence_index"=>"B",
 "journalist_count"=>5,
 "lwin"=>nil,
 "lwin_11"=>nil},

{"wine"=>"Terrazas De Los Andes, 'Cheval Des Andes', Mendoza",
 "wine_id"=>133243,
 "wine_slug"=>"terrazas-de-los-andes-cheval-des-andes-mendoza",
 "appellation"=>"Mendoza",
 "appellation_slug"=>"mendoza",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["Mendoza"],
 "country"=>"Argentina",
 "classification"=>nil,
 "vintage"=>"2014",
 "date"=>"2018-10-31",
 "is_primeurs"=>false,
 "score"=>93.91,
 "confidence_index"=>"A",
 "journalist_count"=>4,
 "lwin"=>1083233,
 "lwin_11"=>10832332014},

{"wine"=>"Merryvale, Profile, Napa Valley",
 "wine_id"=>104738,
 "wine_slug"=>"merryvale-profile-napa-valley",
 "appellation"=>"Napa Valley",
 "appellation_slug"=>"napa-valley",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["California"],
 "country"=>"Usa",
 "classification"=>nil,
 "vintage"=>"2015",
 "date"=>"2018-10-31",
 "is_primeurs"=>false,
 "score"=>91.8,
 "confidence_index"=>"B",
 "journalist_count"=>3,
 "lwin"=>nil,
 "lwin_11"=>nil},

{"wine"=>"Badia A Coltibuono, Chianti Classico Riserva",
 "wine_id"=>7869,
 "wine_slug"=>"badia-a-coltibuono-chianti-classico-riserva",
 "appellation"=>"Chianti Classico Riserva",
 "appellation_slug"=>"chianti-classico-riserva",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["Tuscany"],
 "country"=>"Italy",
 "classification"=>nil,
 "vintage"=>"2013",
 "date"=>"2018-10-31",
 "is_primeurs"=>false,
 "score"=>91.62,
 "confidence_index"=>"C+",
 "journalist_count"=>3,
 "lwin"=>nil,
 "lwin_11"=>nil},

{"wine"=>
  "Marchesi Antinori, Tenuta Tignanello, Marchese Antinori, Chianti Classico Riserva",
 "wine_id"=>147374,
 "wine_slug"=>
  "marchesi-antinori-tenuta-tignanello-marchese-antinori-chianti-classico-riserva",
 "appellation"=>"Chianti Classico Riserva",
 "appellation_slug"=>"chianti-classico-riserva",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["Tuscany"],
 "country"=>"Italy",
 "classification"=>nil,
 "vintage"=>"2015",
 "date"=>"2018-10-31",
 "is_primeurs"=>false,
 "score"=>91.28,
 "confidence_index"=>"B",
 "journalist_count"=>4,
 "lwin"=>1095359,
 "lwin_11"=>10953592015},

{"wine"=>"Merryvale, Cabernet Sauvignon, Napa Valley",
 "wine_id"=>104720,
 "wine_slug"=>"merryvale-cabernet-sauvignon-napa-valley",
 "appellation"=>"Napa Valley",
 "appellation_slug"=>"napa-valley",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["California"],
 "country"=>"Usa",
 "classification"=>nil,
 "vintage"=>"2015",
 "date"=>"2018-10-31",
 "is_primeurs"=>false,
 "score"=>90.22,
 "confidence_index"=>"C+",
 "journalist_count"=>3,
 "lwin"=>nil,
 "lwin_11"=>nil},

{"wine"=>"Tommasi, Casisano, Brunello Di Montalcino",
 "wine_id"=>148107,
 "wine_slug"=>"tommasi-casisano-brunello-di-montalcino",
 "appellation"=>"Brunello Di Montalcino",
 "appellation_slug"=>"brunello-di-montalcino",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["Tuscany"],
 "country"=>"Italy",
 "classification"=>nil,
 "vintage"=>"2013",
 "date"=>"2018-10-31",
 "is_primeurs"=>false,
 "score"=>89.91,
 "confidence_index"=>"A+",
 "journalist_count"=>3,
 "lwin"=>nil,
 "lwin_11"=>nil},

{"wine"=>"Domaine De Marcoux, Vieilles Vignes, Chateauneuf Du Pape",
 "wine_id"=>55441,
 "wine_slug"=>"domaine-de-marcoux-vieilles-vignes-chateauneuf-du-pape",
 "appellation"=>"Chateauneuf Du Pape",
 "appellation_slug"=>"chateauneuf-du-pape",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["Rhone"],
 "country"=>"France",
 "classification"=>nil,
 "vintage"=>"2000",
 "date"=>"2018-09-25",
 "is_primeurs"=>false,
 "score"=>95.02,
 "confidence_index"=>"A+",
 "journalist_count"=>4,
 "lwin"=>1114300,
 "lwin_11"=>11143002000},

{"wine"=>"E. Guigal, Chateau D'Ampuis, Cote Rotie",
 "wine_id"=>68454,
 "wine_slug"=>"e-guigal-chateau-dampuis-cote-rotie",
 "appellation"=>"Cote Rotie",
 "appellation_slug"=>"cote-rotie",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["Rhone"],
 "country"=>"France",
 "classification"=>nil,
 "vintage"=>"2003",
 "date"=>"2018-09-25",
 "is_primeurs"=>false,
 "score"=>93.87,
 "confidence_index"=>"A",
 "journalist_count"=>8,
 "lwin"=>1113172,
 "lwin_11"=>11131722003},

{"wine"=>"Gaja, Conteisa, Langhe",
 "wine_id"=>148324,
 "wine_slug"=>"gaja-conteisa-langhe",
 "appellation"=>"Langhe",
 "appellation_slug"=>"langhe",
 "color"=>"Red",
 "wine_type"=>"",
 "regions"=>["Piedmont"],
 "country"=>"Italy",
 "classification"=>nil,
 "vintage"=>"2014",
 "date"=>"2018-09-24",
 "is_primeurs"=>false,
 "score"=>95.39,
 "confidence_index"=>"B",
 "journalist_count"=>3,
 "lwin"=>1099719,
 "lwin_11"=>10997192014}]
end


def create_wines
  wines = setup_seed_data
  wines.each do |wine|
    wine_url = 'https://www.globalwinescore.com/wine-score/' + wine["wine_slug"]
    Wine.create(name: wine['wine'],color: wine['color'], country: wine['country'],year: wine['vintage'],score: wine['score'], url: wine_url)
  end
end

create_wines

def create_users
  10.times do
    User.create(name: Faker::SiliconValley.character)
  end

end

create_users

def setup_review_data
 reviews = [
   {"user_id" => 1, "wine_id" => 1, "content" => "Complex , long but refreshing. A great summer wine", "rating" => 4},
   {"user_id" => 1, "wine_id" => 2, "content" => "Fantastic full bodied", "rating" => 3},
   {"user_id" => 2, "wine_id" => 3, "content" => "Nancy loved it! Powerhouse. Spicey, masculine", "rating" => 2},
   {"user_id" => 2, "wine_id" => 4, "content" => "Good, drinkable wine. Easy on the pallet. Dinner with sales team at Fogo de Chao.", "rating" => 1},
   {"user_id" => 3, "wine_id" => 5, "content" => "2011 for €45 in Rome. I thought it was a little light. Could have a little more body and years of aging.", "rating" => 5},
   {"user_id" => 4, "wine_id" => 6, "content" => "Perfect!", "rating" => 2},
   {"user_id" => 5, "wine_id" => 7, "content" => "If you prefer a heartier red, choose this", "rating" => 1},
   {"user_id" => 6, "wine_id" => 8, "content" => "We picked it up for the distinctive label", "rating" => 2},
   {"user_id" => 7, "wine_id" => 9, "content" => "dry and refreshing", "rating" => 2},
   {"user_id" => 8, "wine_id" => 10,"content" => "this reserve bubbly is full-bodied", "rating" => 3},
   {"user_id" => 1, "wine_id" => 9,"content" => "This wine is light with a pleasant touch of sweetness
", "rating" => 4},
   {"user_id" => 2, "wine_id" => 8,"content" => "tastes especially fresh", "rating" => 1},
   {"user_id" => 3, "wine_id" => 7,"content" => "strikes a nice balance", "rating" => 2},
   {"user_id" => 4, "wine_id" => 2,"content" => "strikes a nice balance", "rating" => 5},
   {"user_id" => 5, "wine_id" => 2,"content" => "We like the intense raspberry flavor and low alcohol", "rating" => 2},
   {"user_id" => 6, "wine_id" => 2,"content" => "Black cherry and chocolate come to mind", "rating" => 3},
   {"user_id" => 7, "wine_id" => 2,"content" => "We like the pear aromas and subtle sweetness", "rating" => 4},
   {"user_id" => 8, "wine_id" => 2,"content" => "We like the mild sweetness and slight fizz", "rating" => 3},
   {"user_id" => 9, "wine_id" => 2,"content" => "toasty Champagne-like notes", "rating" => 5},
   {"user_id" => 10, "wine_id" => 2,"content" => "Elegant, sophisticated, and pretty", "rating" => 3},
   {"user_id" => 1, "wine_id" => 2,"content" => "soft, balanced sweetness", "rating" => 4},
   {"user_id" => 2, "wine_id" => 4,"content" => "melon notes and full body
", "rating" => 1},
   {"user_id" => 3, "wine_id" => 4,"content" => "Yes, you can get high quality, tasty wine from a box", "rating" => 5},
   {"user_id" => 4, "wine_id" => 4,"content" => "Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins", "rating" => 2},
   {"user_id" => 5, "wine_id" => 4,"content" => "Ripe aromas of fig, blackberry and cassis are softened and sweetened by a slathering of oaky chocolate and vanilla. This is full, layered, intense and cushioned on the palate", "rating" => 3},
   {"user_id" => 6, "wine_id" => 4,"content" => "tremendously delicious, balanced and complex botrytised white", "rating" => 4},
   {"user_id" => 7, "wine_id" => 4,"content" => "Aromatic, dense and toasty, it deftly blends aromas and flavors", "rating" => 5},
   {"user_id" => 8, "wine_id" => 4,"content" => "It has structure, density and considerable acidity that is still calming down. With 18 months in wood", "rating" => 1},
   {"user_id" => 9, "wine_id" => 4,"content" => "Deep, dense and pure from the opening bell", "rating" => 2},
   {"user_id" => 10, "wine_id" => 4,"content" => "Aromas of dark ripe black fruits are cool and moderately oaked. This feels massive on the palate but sensationally balanced.", "rating" => 5},
   {"user_id" => 1, "wine_id" => 5,"content" => "Slightly gritty black-fruit aromas include a sweet note of pastry along with a hint of prune", "rating" => 3},
   {"user_id" => 2, "wine_id" => 5,"content" => "Wall-to-wall saturation ensures that all corners of one's mouth are covered. Flavors of blackberry", "rating" => 3},
   {"user_id" => 3, "wine_id" => 5,"content" => "Lush cedary black-fruit aromas are luxe and offer notes of marzipan and vanilla. This bruiser is massive and tannic on the palate, but still lush and friendly.", "rating" => 3},
   {"user_id" => 4, "wine_id" => 5,"content" => "You'll find striking minerality underscoring chunky black fruits. Accents of citrus and graphite comingle, with exceptional midpalate", "rating" => 3},
   {"user_id" => 5, "wine_id" => 5,"content" => "The producer sources from two blocks of the vineyard for this wine—one at a high elevation, which contributes bright acidity. Crunchy cranberry, pomegranate and orange peel flavors ", "rating" => 3},
   {"user_id" => 6, "wine_id" => 5,"content" => "Elegance, complexity and structure come together in this drop-dead gorgeous winethat ranks among the world's greatest whites. It opens with sublime yellow spring flower", "rating" => 3},
   {"user_id" => 7, "wine_id" => 5,"content" => "this supple well-balanced effort blends flavors of mocha, cherry, vanilla and breakfast tea.", "rating" => 3},
   {"user_id" => 8, "wine_id" => 5,"content" => "This wine is in peak condition", "rating" => 3},
   {"user_id" => 9, "wine_id" => 5,"content" => "The fruit is all there as well: dried berries and hints of black-plum skins.", "rating" => 2},
   {"user_id" => 10, "wine_id" => 5,"content" => "With its sophisticated mix of mineral, acid and tart fruits, this seductive effort pleases from start to finish.", "rating" => 1},
   {"user_id" => 1, "wine_id" => 3,"content" => "	First made in 2006, this succulent luscious wine is all about minerality.", "rating" => 1},
   {"user_id" => 2, "wine_id" => 3,"content" => "It's got a rich core of butterscotch and the seemingly endless layers of subtle flavors", "rating" => 2},
   {"user_id" => 3, "wine_id" => 3,"content" => "	This blockbuster, powerhouse of a wine suggests blueberry pie and chocolate as it opens in the glass.", "rating" => 4},
   {"user_id" => 4, "wine_id" => 3,"content" => "On the palate, it's smooth and seductively silky, offering complex cedar", "rating" => 5},
   {"user_id" => 5, "wine_id" => 3,"content" => "Nicely oaked blackberry, licorice, vanilla and charred aromas are smooth and sultry.", "rating" => 5},
   {"user_id" => 6, "wine_id" => 3,"content" => "Nicely oaked blackberry, licorice, vanilla and charred aromas are smooth and sultry.", "rating" => 3},
   {"user_id" => 7, "wine_id" => 3,"content" => "Forward barrel-spice and mocha flavors", "rating" => 3},
   {"user_id" => 8, "wine_id" => 6,"content" => "this is a magnificent wine. Powered by both fruit tannins and the 28 months of new wood aging, it is darkly rich", "rating" => 5},
   {"user_id" => 9, "wine_id" => 6,"content" => "This fresh and lively medium-bodied wine is beautifully crafted, with cherry blossom aromas and tangy acidity. Layered and seductive", "rating" => 3},
   {"user_id" => 10, "wine_id" => 6,"content" => "Ruby grapefruit-red, it's sultry with strawberry, watermelon, orange zest and salty spice flavor", "rating" => 3},
   {"user_id" => 1, "wine_id" => 6,"content" => "Alluring, complex and powerful aromas of grilled meat, berries, tea, smoke, vanilla and spice cover every base. An intense palate is concentrated but still elegant. Blackberry, molasses", "rating" => 1},
   {"user_id" => 2, "wine_id" => 6,"content" => "Tarry blackberry and cheesy oak aromas are appropriate for a wine of this size and magnitude", "rating" => 3},
   {"user_id" => 3, "wine_id" => 6,"content" => "The apogee of this ambitious winery's white wine efforts, this bottling of just two barrels of Clone 5 shows focused marzipan, marcona almond and white peach notes on the nose", "rating" => 2},
   {"user_id" => 4, "wine_id" => 6,"content" => "Adam Comartin heads 1,100 feet up into the mountains to source fruit for this tremendous wine", "rating" => 3},
   {"user_id" => 5, "wine_id" => 7,"content" => "medium-bodied, silky wine the potential to drink well through at least 2025. Hickory smoke outlines white peach", "rating" => 3},
   {"user_id" => 6, "wine_id" => 7,"content" => "Here are lovely aromatics, with grape jelly, rose petals and plum in the nose", "rating" => 3},
   {"user_id" => 7, "wine_id" => 7,"content" => "Focused and dense, this intense wine captures the essence of ripe raspberries. Aged in 50% new French oak, it's got a strong vein of coffee and mocha.", "rating" => 3},
   {"user_id" => 8, "wine_id" => 7,"content" => "The palate abounds with energy, driving black raspberry fruit ", "rating" => 3},
   {"user_id" => 9, "wine_id" => 7,"content" => "earth shaking aromas of black-olive brine, tapenade, green olive, stargazer lilies, orange peel and crushed gravel", "rating" => 3},
   {"user_id" => 10, "wine_id" => 7,"content" => "In the mouth it is balanced with soft tannins mingling", "rating" => 3},
   {"user_id" => 1, "wine_id" => 8,"content" => "Steely and perfumed, this wine sees only 20% new French oak", "rating" => 4},
   {"user_id" => 2, "wine_id" => 8,"content" => "Pale in color, this is nutty in character, with a warm and rounded hint of red fruits", "rating" => 3},
   {"user_id" => 3, "wine_id" => 8,"content" => "The palate is generous in flavor and feel, showing a fine sense of balance", "rating" => 3},
   {"user_id" => 4, "wine_id" => 8,"content" => "Forest floor, tilled soil, mature berry and a whiff of new leather combine on this. The ripe palate offers fleshy black cherry, dried aromatic herb and tobacco, while fine-grained tannins", "rating" => 3},
   {"user_id" => 5, "wine_id" => 8,"content" => "Gingery spice notes accent fresh pear and melon fruit in this medium- to full-bodied wine", "rating" => 3},
   {"user_id" => 6, "wine_id" => 9,"content" => "This comes across wide and expansive as it lazily exudes oily aromas of hazelnut and toffee", "rating" => 5},
   {"user_id" => 7, "wine_id" => 9,"content" => "A plump palate is not overly cutting or demanding, while flavors of lightly salted nuts and buttered toast", "rating" => 3},
   {"user_id" => 8, "wine_id" => 9,"content" => "This is an aromatic brooder with aromas of scorched earth, plum, dried flowers and green herbs.", "rating" => 3},
   {"user_id" => 9, "wine_id" => 9,"content" => "Aromas of dark-skinned berry, rose and wild herb lead the nose", "rating" => 3},
   {"user_id" => 10, "wine_id" => 9,"content" => "Sunbaked earth, ripe berry, baking spice and a whiff of menthol meld in the glass. The juicy palate offers red cherry, pomegranate, star anise, mocha and a hint of tobacco alongside fine-grained tannins", "rating" => 4},
   {"user_id" => 1, "wine_id" => 10,"content" => "this is a perennial classic for the winery", "rating" => 3},
   {"user_id" => 2, "wine_id" => 10,"content" => "opens with aromas of espresso, plum cake, toast and dark spice. The hearty palate offers blackberry jam, licorice, vanilla and mocha alongside firm fine-grained tannins", "rating" => 3},
   {"user_id" => 3, "wine_id" => 10,"content" => "packed with minerality and considerable weight. The tight texture and almost tannic character will soften over the next few months", "rating" => 2},
   {"user_id" => 4, "wine_id" => 10,"content" => "With its light color and cool feel, this well-balanced wine comes from a parcel of 30-year-old vines", "rating" => 2},
   {"user_id" => 5, "wine_id" => 10,"content" => "There's a lot to like in this nicely priced white, a blend of several regional vineyards. A taste of hazelnut expands on the palate to meet creamy Tahitian vanilla", "rating" => 2},
   {"user_id" => 6, "wine_id" => 10,"content" => "wood spice aromas start out up front", "rating" => 1},
   {"user_id" => 7, "wine_id" => 10,"content" => "Delicious while also young and textured, this wine comes from biodynamically grown grapes", "rating" => 1},
   {"user_id" => 8, "wine_id" => 10,"content" => "While exuberantly fruity, almost tropical on the nose, there's a crystalline edge", "rating" => 1},
   {"user_id" => 9, "wine_id" => 10,"content" => "aromas of roasted coffee bean, leather, tobacco and dark woodland berry", "rating" => 3},
   {"user_id" => 10, "wine_id" => 10,"content" => "Concentrated, ripe blackberry and cassis aromas come with peppery spice and cedary oak notes. This is big and generous on the palate", "rating" => 3},
   {"user_id" => 1, "wine_id" => 10,"content" => "This feels lively on the palate, albeit tartaric. Oaky plum, cassis and vanilla flavors finish full", "rating" => 3},
   {"user_id" => 2, "wine_id" => 10,"content" => "This is a super-ripe, still very young wine. It's showing all its concentrated fruits, wood aging flavors and dense texture as well as the firm tannins that will allow it to age", "rating" => 3},
 ]
end

def create_reviews
  reviews = setup_review_data
  reviews.each do |review|
    Review.create(user_id: review['user_id'], wine_id: review['wine_id'], content: review['content'], rating: review['rating'])
  end
end
create_reviews
